### ISSUE TITLE
File "magazzino"

### ISSUE THREAD

**Issue by Vik28** [claudio-unipv/Progetto-A#3]
- Creare un file "magazzino" contenente un elenco di oggetti (lotti) da vendere. 
Il file deve avere un formato di questo tipo:

lotto X TAB nome oggetto TAB descrizione TAB prezzo base TAB prezzo di riserva
esempio:

```
1    lcd    schermo    bellissimo    1    500
2    mouse    mouse incredibilmente preciso sottosopra    450    1235
...
...
...
```

Creare ALMENO una decina di oggetti di qualsiasi tipo.

**Comment by lucad93** [comment]
Ometterei la parola "lotto" poiché ridondante.

**Comment by Vik28** [comment]
@lucad93 Fatto.
