### ISSUE TITLE
Interfaccia grafica: Java o HTML?

### ISSUE THREAD

**Issue by Vik28** [claudio-unipv/Progetto-A#5]
Ho iniziato a comporre l'interfaccia grafica per lo step n°1 MA c'è una questione da decidere, ovvero:
## Quale linguaggio di programmazione utilizziamo per il lato "client"?  
La prima risposta può essere "facciamolo in java!!!" per i più svariati motivi (il corso era in java, esame è in java) ma bisogna tener conto di un paio di cose.

Il lato _**client**_ in java (per me) non è complicato da sviluppare fino ad un certo punto (per esempio il codice per la versione per lo step 1 l'ho già scritto in un progetto che ho creato per test) ma più lo si vuole "_bello da vedere_" e _dettagliato_ più questo diventa complesso, o meglio, più questo richiede **tempo** da dedicarci!  
Ma ora mettiamo in gioco anche il concetto di "**pro & contro**"...ovvero:
### Java  
Pro:
- corso in Java -> più codice in Java (ma questo lato riguarda solo chi gestisce l'interfaccia grafica)
- un solo linguaggio da conoscere
- interfaccia grafica **elementare** -> _semplice_ da implementare  

Contro:
- per il trasferimento di dati tra client e server bisogna utilizzare direttamente i **socket di rete** (necessità di inventare un _protocollo_ adeguato e di gestire casi come per esempio "caduta della connessione, un utente che effettua un logout imprevisto, tenere traccia delle sessioni aperte...)
- interfaccia grafica **non banale** -> complessità molto _elevata_ rispetto ad _html_

### HTML
Pro:
- più semplice, o meglio, più intuitivo (**per tutti**)
- protocolli (_http_) **standard** (quello è e quello si usa)
- non serve un "_.exe / .jar_"(molto portatile in quanto serve **solo** un browser web)
- più semplice gestire animazioni o più in generale un'interfaccia grafica più _gradevole_  

Contro:
- il lato **server** (il server ricordo che è in linguaggio _Java)_ deve contenere un server web e di conseguenza deve potersi interfacciare con una _libreria_ che fornisce funzionalità "http"
- dal punto precedente si evince che bisognerà utilizzare una libreria esterna _adeguata_ (bene o male la documentazione è sempre semplice da trovare)  
  
Io personalmente opterei per **HTML** (lato client naturalmente) per portabilità e semplicità grafiche, si crea quindi il _"problema"_ di utilizzare una libreria esterna ma (sotto consiglio di _Luca_ -non Defilippi-) esiste una libreria chiamata _Netty,_ di cui andrò a leggere la documentazione (vi chiedo di fare lo stesso) pur tenendo conto che ne esistono a bizzeffe di librerie! Se non dovesse piacere Netty se ne troverà un'altra...  
  
La questione è: mettiamola ai voti!  
Quale utilizziamo?  
@lucad93 @farina311 @bipavesi @alessandro-galluzzi

**Comment by alessandro-galluzzi** [comment]
Sembra che html sia la soluzione più semplice da implementare e se è disponibile già una libreria che implementa già le funzionalità che ci servono non dovrebbe essere troppo difficile usarla. Inoltre da quello che hai scritto usando java dovremmo creare un nuovo protocollo ma credo che usare l'http sia meglio dato che è standard. Per la questione di un solo linguaggio da conoscere html non dovrebbe essere un linguaggio di programmazione (a meno che non conti anche altre cose come un linguaggio di scripting per creare le pagine o javascript per eseguire codice sul client) e per creare le pagine in html so che esistono dei programmi grafici. Quindi anche io voto per l'html

**Comment by lucad93** [comment]
Io propongo di restare su Java. Come detto sopra l'esame sarà in Java, e secondo me vale di più la pena sbattere la testa per capire come sviluppare alcuni casi difficili in quel linguaggio che perdere del tempo ad imparare e capire qualcosa di nuovo (e praticamente non richiesto all'esame), quale è l'HTML (ed eventuale Javascript).

**Comment by Vik28** [comment]
@lucad93 Ma qui si tratta solo della parte client, cioè interfaccia grafica ed esclusivamente l'utilizzo di una libreria per far capire al server (da fare in Java) come utilizzare i dati forniti da protocollo http

**Comment by Vik28** [comment]
Comunque aspettiamo anche la risposta di @farina311 e poi ne discuteremo anche in aula martedi :) certo è che con martedi dovremo avere le idee chiare bene o male su molte cose

**Comment by Vik28** [comment]
@farina311 attendiamo una tua risposta :)
